package main

var prods = map[string]string{
	"google_compute_firewall":                "compute firewalls",
	"google_compute_instance":                "compute instances",
	"google_pubsub_topic":                    "pubsub topics",
	"google_cloud_run_service":               "run services",
	"google_storage_bucket":                  "TODO: Replace with gsutil command",
	"google_storage_bucket_object":           "TODO: Replace with gsutil command",
	"google_cloudfunctions_function":         "functions",
	"google_composer_environment":            "composer environments",
	"google_bigquery_dataset":                "TODO: Replace with bq command",
	"google_bigquery_table":                  "TODO: Replace with bq command",
	"google_compute_snapshot":                "compute snapshots",
	"google_compute_image":                   "compute images",
	"google_compute_instance_template":       "compute instance-templates",
	"google_compute_instance_group_manager":  "compute instance groups managed",
	"google_compute_global_address":          "compute addresses ",
	"google_compute_health_check":            "compute health-checks",
	"google_compute_backend_service":         "compute backend-service",
	"google_compute_url_map":                 "compute url-maps",
	"google_compute_target_http_proxy":       "compute target-http-proxies",
	"google_compute_forwarding_rule":         "compute forwarding-rules",
	"google_dns_managed_zone":                "gcloud dns record-sets describe",
	"google_compute_managed_ssl_certificate": "compute ssl-certificate",
	"google_compute_backend_bucket":          "compute backend-buckets ",
	"google_compute_target_https_proxy":      "compute target-https-proxies",
	"google_dns_record_set":                  "gcloud dns record-sets describe",
	"google_artifact_registry_repository":    "artifacts repositories",
	"google_compute_network":                 "compute networks",
	"google_vpc_access_connector":            "compute networks vpc-access connectors",
	"google_sql_database_instance":           "sql instances",
	"google_redis_instance":                  "redis instances",
	"google_secret_manager_secret":           "secrets",
}
